import { a } from "@aws-amplify/backend";

/** Generated by CloudIgniter Resource Studio. Do not edit directly. */
const BookDataEntitySchema = {
  Book: a
    .model({
      PK: a.string().required(),
      SK: a.string().required(),
      id: a.id().required(),
      ciScopeKey: a.string().required(),
      ciSortKey: a.string().required(),
      title: a.string().required(),
      price: a.float(),
    })
    .identifier(["PK", "SK"])
    .secondaryIndexes((index) => [
      index("ciScopeKey")
        .sortKeys(["ciSortKey"])
        .name("byScope")
        .queryField("listBooksByScope")
        .projection("ALL"),
    ])
    .authorization((allow) => [
      allow
        .groups(["system-admin", "system-super-admin"])
        .to(["create", "read", "update", "delete"]),
    ]),
};

export default BookDataEntitySchema;
