export const ENV = {
  REGION: 'CI_REGION',

  SYSTEM_TABLE_NAME: 'CI_SYSTEM_TABLE_NAME',
  SYSTEM_TABLE_ARN: 'CI_SYSTEM_TABLE_ARN',

  USER_PROFILE_TABLE_NAME: 'CI_USER_PROFILE_TABLE_NAME',
  USER_PROFILE_TABLE_ARN: 'CI_USER_PROFILE_TABLE_ARN',

  USER_POOL_ID_PARAM: 'CI_USER_POOL_ID_PARAM',
  USER_POOL_ARN_PARAM: 'CI_USER_POOL_ARN_PARAM',
  USER_POOL_ID: 'CI_USER_POOL_ID',
  USER_POOL_ARN: 'CI_USER_POOL_ARN',
} as const;
