import { ciMergeAmplifyDataSchemas } from "@cloudigniter/aws/server/backend";

/** Generated by CloudIgniter Resource Studio. Do not edit directly. */
const generatedDataEntitySchemas = ciMergeAmplifyDataSchemas({});

export default generatedDataEntitySchemas;
