import { CI_DEFAULT_REQUEST_CONTEXT_HEADER_NAME, ciDeserializeRequestContext } from "@ci-core/lib";

import type { CiTenantContext } from "@ci-core/types";

/**
 * Reads the resolved tenant context generated by the proxy.
 */
export function ciReadTenantFromHeaders(
  requestHeaders: Headers,
  headerName = CI_DEFAULT_REQUEST_CONTEXT_HEADER_NAME,
): CiTenantContext {
  const serializedContext = requestHeaders.get(headerName);

  if (!serializedContext) {
    throw new Error(`The required request-context header "${headerName}" is missing.`);
  }

  return ciDeserializeRequestContext(serializedContext).tenant;
}
