// Generated by CloudIgniter Modules. Do not edit.
"use client";
import type { ComponentType } from "react";
import type { CiExtensionPageProps } from "@cloudigniter/ui/types";
import { CiModulePage as m0 } from "../todo/client";
export const extensionPages: Record<string, ComponentType<CiExtensionPageProps>> = {"todo": m0};
