import { lstat, readFile, writeFile } from "node:fs/promises";
import {
  ciCompileSmartForm,
  ciGenerateSmartFormModule,
} from "../src/lib/smart-form/ci-smart-form";
import {
  CI_USER_CREATE_FORM_SPEC,
  CI_USER_EDIT_FORM_SPEC,
  CI_USER_FORM_TEMPLATE,
  CI_USER_EDIT_FORM_TEMPLATE,
} from "../src/lib/smart-form/ci-user-form-definitions";

const source = ciGenerateSmartFormModule({
  userCreate: ciCompileSmartForm(
    CI_USER_CREATE_FORM_SPEC,
    CI_USER_FORM_TEMPLATE,
  ),
  userEdit: ciCompileSmartForm(
    CI_USER_EDIT_FORM_SPEC,
    CI_USER_EDIT_FORM_TEMPLATE,
  ),
});
const target = new URL(
  "../src/lib/smart-form/ci-core-forms.generated.ts",
  import.meta.url,
);
const existing = await lstat(target).catch((error: NodeJS.ErrnoException) => {
  if (error.code === "ENOENT") return undefined;
  throw error;
});
if (existing && (!existing.isFile() || existing.isSymbolicLink()))
  throw new Error(
    "The generated form target must be a regular file, not a symlink.",
  );
const previous = await readFile(target, "utf8").catch(
  (error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined;
    throw error;
  },
);
if (
  previous !== undefined &&
  !previous.startsWith("// Generated by CloudIgniter Smart Forms.")
)
  throw new Error("Refusing to overwrite a manually owned file.");
if (source !== previous) await writeFile(target, source);
