import type { DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";
import type { CloudFormationClient } from "@aws-sdk/client-cloudformation";
import type {
  CiExtensionConfiguration,
  CiExtensionManifest,
  CiExtensionSnapshot,
} from "@cloudigniter/core/types";
import type { CiAppSyncResolverEvent } from "@ci-aws/types";

export type CiAwsExtensionDefinition = {
  manifest: CiExtensionManifest;
  /** Trusted, bundled provider facet; never supplied by a browser. */
  template?(tableName: string): Record<string, unknown>;
  execute?(
    input: unknown,
    context: CiAwsExtensionExecutionContext,
  ): Promise<unknown>;
};
export type CiAwsExtensionExecutionContext = {
  actorId: string;
  moduleId: string;
  tableName: string;
  controlTableName: string;
  snapshot: CiExtensionSnapshot;
  configuration: CiExtensionConfiguration;
  client: DynamoDBDocumentClient;
  assertAccess(permission: string): Promise<void>;
};
export type CiAwsExtensionProviderOptions = {
  client: CloudFormationClient;
  definitions: readonly CiAwsExtensionDefinition[];
  /** Unique to the deployed application/environment; generated by backend composition. */
  prefix: string;
  account: string;
  region: string;
  partition: string;
  serviceRoleArn: string;
};
export type CiAwsExtensionHandlersOptions = {
  framework: string;
  definitions: readonly CiAwsExtensionDefinition[];
  client?: DynamoDBDocumentClient;
  cloudFormation?: CloudFormationClient;
};
export type CiAwsExtensionHandler = (
  event: CiAppSyncResolverEvent,
) => Promise<unknown>;
export type CiAwsExtensionPoliciesOptions = {
  prefix: string;
  ids: readonly string[];
  partition: string;
  region: string;
  account: string;
};
