export {
  CI_CORE_ROLE_PRECEDENCE,
  CI_CORE_ROLES_BY_PRECEDENCE,
  ciResolvePrimaryRole,
} from "./ci-role-precedence";
export {
  ciAccessScopeContains,
  ciAssertValidAccessControlDefinition,
  ciAuthorize,
  ciCan,
  ciCanAll,
  ciCanAny,
  ciCanOverrideCoreAccessControl,
  ciApplyCoreAccessControlOverrides,
  ciCreateAppAccessControl,
  ciCreateAppAuthorizer,
  ciCreateAuthorizationSubject,
  ciCreateAuthorizer,
  ciCreateCoreAccessControlOverride,
  ciCreateCoreAccessControl,
  ciCreateRoleAssignment,
  ciCreateRoleAssignments,
  ciCreateRoleAssignmentsFromIdentityGroups,
  ciCreateSecurityAdministration,
  ciBuildSecurityRoleCounters,
  ciCreateScopedPrivilege,
  ciDefineAccessControl,
  ciFormatPermission,
  ciGlobalAccessScope,
  ciGetAccessControlEntryOrigin,
  ciIsCoreAccessControlEntry,
  ciIsAccessControlKebabIdentifier,
  ciMatchesAuthorizationPattern,
  ciMatchesPermission,
  ciMergeAccessControlDefinitions,
  ciMigrateLegacyPrivilegeTitles,
  ciOrgUnitAccessScope,
  ciParsePermission,
  ciResolveIdentityGroupRoles,
  ciSystemAccessScope,
  ciTenantAccessScope,
  ciValidateAccessControlDefinition,
} from "@cloudigniter/emberguard/lib";
export {
  CI_ACCESS_CONTROL_KEBAB_IDENTIFIER_PATTERN,
  CI_DEFAULT_ACCESS_CONTROL_DEFINITION,
} from "@cloudigniter/emberguard/lib";
