#!/usr/bin/env node

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
const packageRoot = process.cwd();
const themeRoot = path.join(packageRoot, "src", "styles", "standard", "theme");

const outputFileName = "theme.generated.css";
const outputFilePath = path.join(themeRoot, outputFileName);

/**
 * Defines the cascade order for the main theme folders.
 *
 * Any folder not listed here is appended alphabetically after these folders.
 * Keep lower-level foundation tokens before semantic and component-level styles.
 */
const folderOrder = [
  "foundation",
  "palette",
  "tokens",
  "semantic",
  "design",
  "layout",
  "components",
  "utilities",
];

/**
 * Returns every CSS file inside a directory recursively, in deterministic order.
 */
async function getCssFiles(directoryPath) {
  const entries = await readdir(directoryPath, { withFileTypes: true });

  const directories = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const files = entries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith(".css") &&
        entry.name !== outputFileName,
    )
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right));

  const nestedFiles = await Promise.all(
    directories.map((directoryName) =>
      getCssFiles(path.join(directoryPath, directoryName)),
    ),
  );

  return [
    ...files.map((fileName) => path.join(directoryPath, fileName)),
    ...nestedFiles.flat(),
  ];
}

/**
 * Orders root-level theme folders according to the defined cascade order.
 */
function sortThemeFolders(folderNames) {
  return [...folderNames].sort((left, right) => {
    const leftIndex = folderOrder.indexOf(left);
    const rightIndex = folderOrder.indexOf(right);

    const leftRank = leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex;
    const rightRank = rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex;

    if (leftRank !== rightRank) {
      return leftRank - rightRank;
    }

    return left.localeCompare(right);
  });
}

async function buildTheme() {
  const themeEntries = await readdir(themeRoot, { withFileTypes: true });

  const rootCssFiles = themeEntries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith(".css") &&
        entry.name !== outputFileName,
    )
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right))
    .map((fileName) => path.join(themeRoot, fileName));

  const themeFolders = sortThemeFolders(
    themeEntries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name),
  );

  const nestedCssFiles = (
    await Promise.all(
      themeFolders.map((folderName) =>
        getCssFiles(path.join(themeRoot, folderName)),
      ),
    )
  ).flat();

  const cssFiles = [...rootCssFiles, ...nestedCssFiles];

  if (cssFiles.length === 0) {
    throw new Error(`No CSS files were found in: ${themeRoot}`);
  }

  const sections = await Promise.all(
    cssFiles.map(async (filePath) => {
      const css = await readFile(filePath, "utf8");
      const relativePath = path.relative(packageRoot, filePath);

      return `/* --------------------------------------------------------------------------
 * Source: ${relativePath}
 * -------------------------------------------------------------------------- */

${css.trim()}
`;
    }),
  );

  const output = `/**
 * ----------------------------------------------------------------------------
 * GENERATED FILE — DO NOT EDIT DIRECTLY
 * ----------------------------------------------------------------------------
 * Generated by: ci-dev next build-theme
 * Source directory: src/styles/standard/theme
 * ----------------------------------------------------------------------------
 */

${sections.join("\n")}
`;

  await mkdir(path.dirname(outputFilePath), { recursive: true });
  await writeFile(outputFilePath, output, "utf8");

  console.log(
    `Theme built successfully: ${path.relative(packageRoot, outputFilePath)}`,
  );
  console.log(`Merged ${cssFiles.length} CSS file(s).`);
}

buildTheme().catch((error) => {
  console.error("\nFailed to build the CloudIgniter theme.\n");
  console.error(error);
  process.exitCode = 1;
});
