import { lstat, readFile, readdir, realpath } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ciRunResourceFileTransaction } from "@cloudigniter/cli/runtime/resource-file-transaction";
import {
  ciValidateExtensionManifest,
  ciIsExtensionCompatible,
} from "@cloudigniter/core/lib";
import type { CiExtensionManifest } from "@cloudigniter/core/types";

const marker = "// Generated by CloudIgniter Modules. Do not edit.\n";
/** Build-time discovery of trusted local module source. No downloads, cloud calls, or runtime code loading. */
export async function ciGenerateNextExtensionRegistry(
  applicationRoot: string,
): Promise<void> {
  const root = await realpath(applicationRoot);
  const modules = path.join(root, "src/custom/modules");
  const check = async (target: string, file = false) => {
    const stat = await lstat(target);
    if (
      stat.isSymbolicLink() ||
      (file ? !stat.isFile() : !stat.isDirectory()) ||
      (await realpath(target)) !== target
    )
      throw new Error(
        `Module paths must be regular, confined paths: ${target}`,
      );
  };
  await check(modules);
  const entries: { id: string; manifest: CiExtensionManifest }[] = [];
  for (const entry of (await readdir(modules, { withFileTypes: true })).sort(
    (a, b) => a.name.localeCompare(b.name),
  )) {
    if (entry.name.startsWith(".")) continue;
    if (!entry.isDirectory() || !/^[a-z][a-z0-9-]{0,47}$/.test(entry.name))
      throw new Error(`Unexpected module entry: ${entry.name}`);
    const folder = path.join(modules, entry.name);
    await check(folder);
    await check(path.join(folder, "manifest.ts"), true);
    const imported = await import(
      pathToFileURL(path.join(folder, "manifest.ts")).href
    );
    const manifest: CiExtensionManifest = imported.ciModuleManifest;
    ciValidateExtensionManifest(manifest);
    if (manifest.id !== entry.name)
      throw new Error("Module folder and manifest ID must match.");
    if (
      ciIsExtensionCompatible(manifest, { framework: "next", cloud: "aws" })
    ) {
      if (manifest.runtime.client) {
        await check(path.join(folder, "client"));
        await check(path.join(folder, "client/index.ts"), true);
      }
      if (manifest.runtime.server) {
        await check(path.join(folder, "server"));
        await check(path.join(folder, "server/aws"));
        await check(path.join(folder, "server/aws/index.ts"), true);
      }
    }
    entries.push({ id: entry.name, manifest });
  }
  if (entries.length > 100)
    throw new Error("The module catalogue supports at most 100 extensions.");
  const manifests = entries
    .map(
      (entry, i) =>
        `import { ciModuleManifest as m${i} } from "../${entry.id}/manifest";`,
    )
    .join("\n");
  const compatible = entries.filter((entry) =>
    ciIsExtensionCompatible(entry.manifest, {
      framework: "next",
      cloud: "aws",
    }),
  );
  const clientEntries = compatible.filter(
    (entry) => entry.manifest.runtime.client && entry.manifest.dashboard,
  );
  const clients = clientEntries
    .map(
      (entry, i) =>
        `import { CiModulePage as m${i} } from "../${entry.id}/client";`,
    )
    .join("\n");
  const providers = compatible
    .map((entry, i) =>
      entry.manifest.runtime.server
        ? `import { ciModuleBackend as m${i} } from "../${entry.id}/server/aws";`
        : `import { ciModuleManifest as manifest${i} } from "../${entry.id}/manifest";\nconst m${i} = { manifest: manifest${i} };`,
    )
    .join("\n");
  const output = {
    "manifests.ts": `${marker}${manifests}\nexport const extensionManifests = [${entries.map((_, i) => `m${i}`).join(", ")}] as const;\n`,
    "client.ts": `${marker}\"use client\";\nimport type { ComponentType } from "react";\nimport type { CiExtensionPageProps } from "@cloudigniter/ui/types";\n${clients}\nexport const extensionPages: Record<string, ComponentType<CiExtensionPageProps>> = {${clientEntries.map((entry, i) => `${JSON.stringify(entry.id)}: m${i}`).join(", ")}};\n`,
    "aws.ts": `${marker}${providers}\nexport const extensionBackends = [${compatible.map((_, i) => `m${i}`).join(", ")}] as const;\n`,
  };
  const changes: { path: string; content: string; mode: number }[] = [];
  // Preserve the source filesystem's effective file mode (removable volumes may ignore chmod).
  const sourceMode = entries.length
    ? (await lstat(path.join(modules, entries[0]!.id, "manifest.ts"))).mode &
      0o777
    : 0o644;
  for (const [file, content] of Object.entries(output)) {
    const target = path.join(modules, ".generated", file);
    let previous: string | undefined;
    try {
      await check(path.dirname(target));
      await check(target, true);
      previous = await readFile(target, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    if (previous !== undefined && !previous.startsWith(marker))
      throw new Error(
        `Refusing to overwrite a manual module registry: ${target}`,
      );
    if (previous !== content)
      changes.push({
        path: path.relative(root, target),
        content,
        mode:
          previous === undefined
            ? sourceMode
            : (await lstat(target)).mode & 0o777,
      });
  }
  if (changes.length) {
    const result = await ciRunResourceFileTransaction({
      applicationRoot: root,
      changes,
      metadata: { owner: "cloudigniter-modules" },
    });
    if (result.status !== "applied")
      throw new Error(
        "Module registry changed during generation. Retry after resolving the conflict.",
      );
  }
}
