export const CI_ENV = {
  CI_ENV_MODE: 'CI_ENV_MODE',
  CI_REGION: 'CI_REGION',

  // tables
  CI_PRIVATE_SETTINGS_TABLE_NAME: 'CI_PRIVATE_SETTINGS_TABLE',
  CI_PRIVATE_SETTINGS_TABLE_ARN: 'CI_PRIVATE_SETTINGS_TABLE_ARN',

  CI_PUBLIC_SETTINGS_TABLE_NAME: 'CI_PUBLIC_SETTINGS_TABLE',
  CI_PUBLIC_SETTINGS_TABLE_ARN: 'CI_PUBLIC_SETTINGS_TABLE_ARN',

  CI_SYSTEM_TABLE_NAME: 'CI_SYSTEM_TABLE',
  CI_SYSTEM_TABLE_ARN: 'CI_SYSTEM_TABLE_ARN',

  CI_USER_PROFILE_TABLE_NAME: 'CI_USER_PROFILE_TABLE',
  CI_USER_PROFILE_TABLE_ARN: 'CI_USER_PROFILE_TABLE_ARN',

  CI_USER_SETTINGS_TABLE_NAME: 'CI_USER_SETTINGS_TABLE',
  CI_USER_SETTINGS_TABLE_ARN: 'CI_USER_SETTINGS_TABLE_ARN',

  // Environment variable keys required for Cognito-aware handlers.
  CI_USER_POOL_ID_PARAM: 'CI_USER_POOL_ID_PARAM',
  CI_USER_POOL_ARN_PARAM: 'CI_USER_POOL_ARN_PARAM',
  CI_USER_POOL_ID: 'CI_USER_POOL_ID',
  CI_USER_POOL_ARN: 'CI_USER_POOL_ARN',
} as const;

export type CiEnvKey = (typeof CI_ENV)[keyof typeof CI_ENV];
export type CiEnvAllowList = readonly CiEnvKey[];
