import { lstat, readFile, writeFile } from "node:fs/promises";

import {
  ciCompileSmartForm,
  ciGenerateSmartFormModule,
  ciMergeSmartFormSpecifications,
  ciMergeSmartFormTemplates,
  CI_USER_CREATE_FORM_SPEC,
  CI_USER_EDIT_FORM_SPEC,
  CI_USER_FORM_TEMPLATE,
  CI_USER_EDIT_FORM_TEMPLATE,
} from "@cloudigniter/core/lib";
import {
  appUserFormSpecifications,
  appUserFormTemplate,
} from "../user/smart-form";

async function generate() {
  const source = ciGenerateSmartFormModule({
    userCreate: ciCompileSmartForm(
      ciMergeSmartFormSpecifications(
        CI_USER_CREATE_FORM_SPEC,
        appUserFormSpecifications,
      ),
      CI_USER_CREATE_FORM_SPEC.category === "fixed"
        ? CI_USER_FORM_TEMPLATE
        : ciMergeSmartFormTemplates(CI_USER_FORM_TEMPLATE, appUserFormTemplate),
    ),
    userEdit: ciCompileSmartForm(
      ciMergeSmartFormSpecifications(
        CI_USER_EDIT_FORM_SPEC,
        appUserFormSpecifications,
      ),
      CI_USER_EDIT_FORM_SPEC.category === "fixed"
        ? CI_USER_EDIT_FORM_TEMPLATE
        : ciMergeSmartFormTemplates(
            CI_USER_EDIT_FORM_TEMPLATE,
            appUserFormTemplate,
          ),
    ),
  });
  const target = new URL("./smart-forms.generated.ts", import.meta.url);
  const existing = await lstat(target).catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined;
    throw error;
  });
  if (existing && (!existing.isFile() || existing.isSymbolicLink()))
    throw new Error(
      "The generated form target must be a regular file, not a symlink.",
    );
  const previous = await readFile(target, "utf8").catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return undefined;
      throw error;
    },
  );
  if (
    previous !== undefined &&
    !previous.startsWith("// Generated by CloudIgniter Smart Forms.")
  )
    throw new Error("Refusing to overwrite a manually owned file.");
  if (source !== previous) await writeFile(target, source);
}
void generate().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
