// Generated by CloudIgniter Smart Forms. Do not edit.
import type { CiCompiledSmartForm } from "@cloudigniter/core/types";
function freeze<T>(value: T): T {
  if (value !== null && typeof value === "object") {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
}
export const ciGeneratedSmartForms = freeze<{ userCreate: CiCompiledSmartForm; userEdit: CiCompiledSmartForm }>({
  "userCreate": {
    "version": 1,
    "specifications": {
      "id": "ciUserCreate",
      "category": "customizable",
      "groups": [
        {
          "name": "main",
          "label": "Account"
        },
        {
          "name": "profile",
          "label": "CloudIgniter profile",
          "order": 10
        },
        {
          "name": "address",
          "label": "Residence address",
          "order": 20,
          "collapsible": true,
          "defaultCollapsed": true
        },
        {
          "name": "extensions",
          "label": "Profile extensions",
          "order": 30
        },
        {
          "name": "access",
          "label": "Identity roles",
          "order": 40
        }
      ],
      "fields": [
        {
          "name": "email",
          "label": "Email",
          "required": true,
          "type": {
            "kind": "email"
          },
          "props": {
            "autoComplete": "email"
          }
        },
        {
          "name": "givenName",
          "label": "Given name",
          "required": true,
          "props": {
            "autoComplete": "given-name"
          }
        },
        {
          "name": "familyName",
          "label": "Family name",
          "required": true,
          "props": {
            "autoComplete": "family-name"
          }
        },
        {
          "name": "middleName",
          "label": "Middle name",
          "props": {
            "autoComplete": "additional-name"
          }
        },
        {
          "name": "temporaryPassword",
          "label": "Temporary password",
          "type": {
            "kind": "password"
          },
          "props": {
            "autoComplete": "new-password"
          }
        },
        {
          "name": "sendInvitation",
          "label": {
            "text": "Send invitation message",
            "position": "side"
          },
          "type": {
            "kind": "boolean"
          },
          "defaultValue": true
        },
        {
          "name": "displayName",
          "group": "profile",
          "label": "Display name"
        },
        {
          "name": "title",
          "group": "profile",
          "label": "Title",
          "props": {
            "placeholder": "Dr, Ms, Mr, Prof"
          }
        },
        {
          "name": "gender",
          "group": "profile",
          "label": "Gender",
          "type": {
            "kind": "singleSelect",
            "options": [
              {
                "value": "female",
                "label": "Female"
              },
              {
                "value": "male",
                "label": "Male"
              },
              {
                "value": "non-binary",
                "label": "Non-binary"
              },
              {
                "value": "self-described",
                "label": "Self-described"
              },
              {
                "value": "prefer-not-to-say",
                "label": "Prefer not to say"
              }
            ]
          },
          "props": {
            "placeholder": "Not specified"
          }
        },
        {
          "name": "phoneNumber",
          "group": "profile",
          "label": "Phone number",
          "type": {
            "kind": "tel"
          },
          "props": {
            "autoComplete": "tel"
          }
        },
        {
          "name": "locale",
          "group": "profile",
          "label": "Locale",
          "type": {
            "kind": "singleSelect",
            "optionsSource": "locales"
          },
          "props": {
            "placeholder": "Application default"
          }
        },
        {
          "name": "timeZone",
          "group": "profile",
          "label": "Time zone",
          "type": {
            "kind": "singleSelect",
            "optionsSource": "timeZones"
          },
          "props": {
            "placeholder": "Application default"
          }
        },
        {
          "name": "avatarKey",
          "group": "profile",
          "label": "Profile photo key"
        },
        {
          "name": "avatarUrl",
          "group": "profile",
          "label": "Profile photo URL",
          "type": {
            "kind": "url"
          }
        },
        {
          "name": "addressLine1",
          "group": "address",
          "label": "Address line 1",
          "props": {
            "autoComplete": "address-line1"
          }
        },
        {
          "name": "addressLine2",
          "group": "address",
          "label": "Address line 2",
          "props": {
            "autoComplete": "address-line2"
          }
        },
        {
          "name": "addressLocality",
          "group": "address",
          "label": "City / locality",
          "props": {
            "autoComplete": "address-level2"
          }
        },
        {
          "name": "addressRegion",
          "group": "address",
          "label": "State / region",
          "props": {
            "autoComplete": "address-level1"
          }
        },
        {
          "name": "addressPostalCode",
          "group": "address",
          "label": "Postal code",
          "props": {
            "autoComplete": "postal-code"
          }
        },
        {
          "name": "addressCountryCode",
          "group": "address",
          "label": "Country code",
          "props": {
            "maxLength": 2,
            "autoComplete": "country"
          },
          "validation": {
            "pattern": "^[A-Za-z]{2}$",
            "message": "Use a two-letter country code."
          }
        },
        {
          "name": "profileExtensions",
          "group": "extensions",
          "label": "Additional profile data",
          "type": {
            "kind": "jsonEditor",
            "objectOnly": true
          },
          "defaultValue": {},
          "description": "Application-specific profile values."
        },
        {
          "name": "roles",
          "group": "access",
          "label": "Identity roles",
          "required": true,
          "type": {
            "kind": "multiSelect",
            "display": "checkbox",
            "optionsSource": "roles"
          }
        },
        {
          "name": "department",
          "group": "extensions",
          "label": "Department",
          "props": {
            "placeholder": "Engineering"
          }
        },
        {
          "name": "jobTitle",
          "group": "extensions",
          "label": "Job title"
        }
      ],
      "buttons": [
        {
          "id": "cancel",
          "label": "Cancel",
          "type": "cancel",
          "order": 0
        },
        {
          "id": "save",
          "label": "Create user",
          "type": "create",
          "pendingLabel": "Creating user...",
          "order": 10
        }
      ],
      "errors": {}
    },
    "template": {
      "groups": [
        {
          "name": "main",
          "rows": [
            {
              "id": "email",
              "fields": [
                "email"
              ]
            },
            {
              "id": "names",
              "fields": [
                "givenName",
                "familyName"
              ],
              "columns": 2
            },
            {
              "id": "middle",
              "fields": [
                "middleName"
              ]
            },
            {
              "id": "invitation",
              "fields": [
                "temporaryPassword",
                "sendInvitation"
              ],
              "columns": 2
            }
          ]
        },
        {
          "name": "profile",
          "rows": [
            {
              "id": "display",
              "fields": [
                "displayName"
              ]
            },
            {
              "id": "identity",
              "fields": [
                "title",
                "gender"
              ],
              "columns": 2
            },
            {
              "id": "contact",
              "fields": [
                "phoneNumber",
                "locale"
              ],
              "columns": 2
            },
            {
              "id": "timeZone",
              "fields": [
                "timeZone"
              ]
            },
            {
              "id": "photo",
              "fields": [
                "avatarKey",
                "avatarUrl"
              ],
              "columns": 2
            }
          ]
        },
        {
          "name": "address",
          "rows": [
            {
              "id": "street",
              "fields": [
                "addressLine1",
                "addressLine2"
              ],
              "columns": 2
            },
            {
              "id": "city",
              "fields": [
                "addressLocality",
                "addressRegion"
              ],
              "columns": 2
            },
            {
              "id": "country",
              "fields": [
                "addressPostalCode",
                "addressCountryCode"
              ],
              "columns": 2
            }
          ]
        },
        {
          "name": "extensions",
          "rows": [
            {
              "id": "employment",
              "fields": [
                "department",
                "jobTitle"
              ],
              "columns": 2
            },
            {
              "id": "fieldprofileExtensions",
              "fields": [
                "profileExtensions"
              ],
              "columns": 1
            }
          ]
        },
        {
          "name": "access",
          "rows": [
            {
              "id": "fieldroles",
              "fields": [
                "roles"
              ],
              "columns": 1
            }
          ]
        }
      ]
    }
  },
  "userEdit": {
    "version": 1,
    "specifications": {
      "id": "ciUserEdit",
      "category": "customizable",
      "groups": [
        {
          "name": "main",
          "label": "Account"
        },
        {
          "name": "profile",
          "label": "CloudIgniter profile",
          "order": 10
        },
        {
          "name": "address",
          "label": "Residence address",
          "order": 20,
          "collapsible": true,
          "defaultCollapsed": true
        },
        {
          "name": "extensions",
          "label": "Profile extensions",
          "order": 30
        },
        {
          "name": "access",
          "label": "Identity roles",
          "order": 40
        }
      ],
      "fields": [
        {
          "name": "email",
          "label": "Email",
          "required": true,
          "type": {
            "kind": "email"
          },
          "props": {
            "autoComplete": "email"
          }
        },
        {
          "name": "givenName",
          "label": "Given name",
          "required": true,
          "props": {
            "autoComplete": "given-name"
          }
        },
        {
          "name": "familyName",
          "label": "Family name",
          "required": true,
          "props": {
            "autoComplete": "family-name"
          }
        },
        {
          "name": "middleName",
          "label": "Middle name",
          "props": {
            "autoComplete": "additional-name"
          }
        },
        {
          "name": "displayName",
          "group": "profile",
          "label": "Display name"
        },
        {
          "name": "title",
          "group": "profile",
          "label": "Title",
          "props": {
            "placeholder": "Dr, Ms, Mr, Prof"
          }
        },
        {
          "name": "gender",
          "group": "profile",
          "label": "Gender",
          "type": {
            "kind": "singleSelect",
            "options": [
              {
                "value": "female",
                "label": "Female"
              },
              {
                "value": "male",
                "label": "Male"
              },
              {
                "value": "non-binary",
                "label": "Non-binary"
              },
              {
                "value": "self-described",
                "label": "Self-described"
              },
              {
                "value": "prefer-not-to-say",
                "label": "Prefer not to say"
              }
            ]
          },
          "props": {
            "placeholder": "Not specified"
          }
        },
        {
          "name": "phoneNumber",
          "group": "profile",
          "label": "Phone number",
          "type": {
            "kind": "tel"
          },
          "props": {
            "autoComplete": "tel"
          }
        },
        {
          "name": "locale",
          "group": "profile",
          "label": "Locale",
          "type": {
            "kind": "singleSelect",
            "optionsSource": "locales"
          },
          "props": {
            "placeholder": "Application default"
          }
        },
        {
          "name": "timeZone",
          "group": "profile",
          "label": "Time zone",
          "type": {
            "kind": "singleSelect",
            "optionsSource": "timeZones"
          },
          "props": {
            "placeholder": "Application default"
          }
        },
        {
          "name": "avatarKey",
          "group": "profile",
          "label": "Profile photo key"
        },
        {
          "name": "avatarUrl",
          "group": "profile",
          "label": "Profile photo URL",
          "type": {
            "kind": "url"
          }
        },
        {
          "name": "addressLine1",
          "group": "address",
          "label": "Address line 1",
          "props": {
            "autoComplete": "address-line1"
          }
        },
        {
          "name": "addressLine2",
          "group": "address",
          "label": "Address line 2",
          "props": {
            "autoComplete": "address-line2"
          }
        },
        {
          "name": "addressLocality",
          "group": "address",
          "label": "City / locality",
          "props": {
            "autoComplete": "address-level2"
          }
        },
        {
          "name": "addressRegion",
          "group": "address",
          "label": "State / region",
          "props": {
            "autoComplete": "address-level1"
          }
        },
        {
          "name": "addressPostalCode",
          "group": "address",
          "label": "Postal code",
          "props": {
            "autoComplete": "postal-code"
          }
        },
        {
          "name": "addressCountryCode",
          "group": "address",
          "label": "Country code",
          "props": {
            "maxLength": 2,
            "autoComplete": "country"
          },
          "validation": {
            "pattern": "^[A-Za-z]{2}$",
            "message": "Use a two-letter country code."
          }
        },
        {
          "name": "profileExtensions",
          "group": "extensions",
          "label": "Additional profile data",
          "type": {
            "kind": "jsonEditor",
            "objectOnly": true
          },
          "defaultValue": {},
          "description": "Application-specific profile values."
        },
        {
          "name": "roles",
          "group": "access",
          "label": "Identity roles",
          "required": true,
          "type": {
            "kind": "multiSelect",
            "display": "checkbox",
            "optionsSource": "roles"
          }
        },
        {
          "name": "department",
          "group": "extensions",
          "label": "Department",
          "props": {
            "placeholder": "Engineering"
          }
        },
        {
          "name": "jobTitle",
          "group": "extensions",
          "label": "Job title"
        }
      ],
      "buttons": [
        {
          "id": "cancel",
          "label": "Cancel",
          "type": "cancel",
          "order": 0
        },
        {
          "id": "save",
          "label": "Save changes",
          "type": "update",
          "pendingLabel": "Saving changes...",
          "order": 10
        }
      ],
      "errors": {}
    },
    "template": {
      "groups": [
        {
          "name": "main",
          "rows": [
            {
              "id": "email",
              "fields": [
                "email"
              ]
            },
            {
              "id": "names",
              "fields": [
                "givenName",
                "familyName"
              ],
              "columns": 2
            },
            {
              "id": "middle",
              "fields": [
                "middleName"
              ]
            }
          ]
        },
        {
          "name": "profile",
          "rows": [
            {
              "id": "display",
              "fields": [
                "displayName"
              ]
            },
            {
              "id": "identity",
              "fields": [
                "title",
                "gender"
              ],
              "columns": 2
            },
            {
              "id": "contact",
              "fields": [
                "phoneNumber",
                "locale"
              ],
              "columns": 2
            },
            {
              "id": "timeZone",
              "fields": [
                "timeZone"
              ]
            },
            {
              "id": "photo",
              "fields": [
                "avatarKey",
                "avatarUrl"
              ],
              "columns": 2
            }
          ]
        },
        {
          "name": "address",
          "rows": [
            {
              "id": "street",
              "fields": [
                "addressLine1",
                "addressLine2"
              ],
              "columns": 2
            },
            {
              "id": "city",
              "fields": [
                "addressLocality",
                "addressRegion"
              ],
              "columns": 2
            },
            {
              "id": "country",
              "fields": [
                "addressPostalCode",
                "addressCountryCode"
              ],
              "columns": 2
            }
          ]
        },
        {
          "name": "extensions",
          "rows": [
            {
              "id": "employment",
              "fields": [
                "department",
                "jobTitle"
              ],
              "columns": 2
            },
            {
              "id": "fieldprofileExtensions",
              "fields": [
                "profileExtensions"
              ],
              "columns": 1
            }
          ]
        },
        {
          "name": "access",
          "rows": [
            {
              "id": "fieldroles",
              "fields": [
                "roles"
              ],
              "columns": 1
            }
          ]
        }
      ]
    }
  }
});
