import type {
  CiGraphQLResponse,
  CiJsonValue,
  CiResponse,
} from "@ci-core/types";
import { ciParseGraphqlResponseData } from "./ci-parse-graphql-response-data";

function isObjectLike(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null;
}

/**
 * Runtime guard for `CiResponse` (both ok and err branches).
 *
 * We intentionally check for the *structural* minimum:
 * - `statusCode` exists and is a number
 * - `body` exists
 *
 * Note:
 * - We do not require `ok` here to remain tolerant of older payloads.
 * - If you want stricter guarding, also assert `'ok' in v` and typeof ok === 'boolean`.
 */
function isResponse(v: unknown): v is CiResponse {
  return (
    isObjectLike(v) &&
    "statusCode" in v &&
    "body" in v &&
    typeof (v as any).statusCode === "number"
  );
}

/**
 * Converts a raw `CiGraphQLResponse` into your canonical `CiResponse` envelope.
 *
 * Why this exists
 * - GraphQL responses can represent failure in multiple ways:
 *   - `errors[]` populated (GraphQL-level errors)
 *   - `data` missing/null (common for delete mutations or resolvers returning nothing)
 * - Additionally, `data` may be:
 *   - already-structured JSON (object/array/primitive)
 *   - a JSON string that needs parsing
 *   - (sometimes) an already-wrapped `CiResponse` returned by your resolver/handler
 *
 * What it returns
 * - Always returns a `CiResponse`:
 *   1) If `errors[]` exist:
 *      - returns a 400 error response with combined error messages
 *      - attaches the original GraphQL response under `debug.response`
 *   2) If `data == null` (no errors):
 *      - returns a 200 ok response with an empty object body
 *      - attaches the original GraphQL response under `debug.response`
 *   3) Otherwise:
 *      - parses/normalizes data via `ciParseGraphqlResponseData`
 *      - if the parsed value is already a `CiResponse`, it is passed through
 *        (and we ensure `debug.response` points to the original GraphQL response)
 *      - else the parsed value is wrapped in a 200 ok `CiResponse`
 *
 * Error handling mode
 * - `critical` is forwarded to `ciParseGraphqlResponseData`:
 *   - `true`  → throws on errors / parse issues
 *   - `false` → returns a 400-shaped error response on parse issues
 *
 * Important:
 * - Your `CiResponseMeta` does **not** include a top-level `response` property.
 *   Use `debug.response` instead.
 */
export function ciParseGraphqlResponse(
  input: CiGraphQLResponse,
  critical: boolean = false,
): CiResponse {
  const { errors, data } = input;

  // 1) GraphQL-level errors (e.g., unauthorized, resolver failure, etc.)
  if (Array.isArray(errors) && errors.length > 0) {
    const errorMessages = errors
      .map((e) =>
        e && typeof e.message === "string" ? e.message : "Unknown error",
      )
      .join("\n");

    return {
      ok: false,
      statusCode: 400,
      body: { error: `GRAPHQL_ERRORS: ${errorMessages}` },

      // CiResponseMeta
      message: "Error(s) generated by GraphQL API",
      // debug: { response: input },
    };
  }

  // 2) No errors and no data → successful response with no payload (common for delete ops)
  if (data == null) {
    return {
      ok: true,
      statusCode: 200,
      body: {},

      // CiResponseMeta
      message: "Successful response with no data.",
      // debug: { response: input },
    };
  }

  // 3) Parse the data. If `critical === false`, ciParseGraphqlResponseData returns a 400 response on parse issues.
  const parsed = ciParseGraphqlResponseData<CiJsonValue | CiResponse>(
    input,
    critical,
  );

  // If ciParseGraphqlResponseData returned a CiResponse (either 200 or 4xx), pass it through.
  if (isResponse(parsed)) {
    // Ensure we keep a pointer to the original GraphQL response (unless already present).
    // const existingDebug = isObjectLike((parsed as any).debug)
    //   ? (parsed as any).debug
    //   : undefined;

    return {
      ...(parsed as CiResponse),
      // debug: {
      //   ...(existingDebug ?? {}),
      //   response: existingDebug?.response ?? input,
      // },
    };
  }

  // Otherwise, wrap the parsed JSON/data in a standard 200 CiResponse.
  return {
    ok: true,
    statusCode: 200,
    body: parsed,

    // CiResponseMeta
    message: "Data returned successfully.",
    // debug: { response: input },
  };
}
