export type CiModuleErrorCode =
  | "INVALID_MANIFEST"
  | "DUPLICATE_MODULE"
  | "MISSING_DEPENDENCY"
  | "CIRCULAR_DEPENDENCY"
  | "INCOMPATIBLE_TARGET"
  | "MISSING_CAPABILITY"
  | "CAPABILITY_CONFLICT"
  | "PACKAGE_DEPENDENCY_CONFLICT";
