import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  commandsSidebar: [
    "index",
    {
      type: "category",
      label: "ci Commands",
      link: { type: "doc", id: "ci/index" },
      items: [{ type: "autogenerated", dirName: "ci" }],
    },
    {
      type: "category",
      label: "dev commands",
      customProps: { audience: "developer" },
      link: { type: "doc", id: "dev/index" },
      items: [{ type: "autogenerated", dirName: "dev" }],
    },
  ],
};

export default sidebars;
