#!/usr/bin/env bash
# Preserve existing tooling; register a local skill only when no reachable skill exists.
# This prepares the tool/skill only. Semantic graph generation is a separate agent task.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT"
ALLOW_INSTALL=0
case "${1:-}" in --install-tool) ALLOW_INSTALL=1;; '') :;; *) echo 'Usage: bash scripts/setup-graphify.sh [--install-tool]' >&2; exit 2;; esac
[ "$#" -le 1 ] || exit 2
if [ -L "$ROOT/docs" ] || [ -L "$ROOT/docs/graphify-setup-status.txt" ]; then
  echo 'Refusing a symlinked status output.' >&2; exit 1
fi
mkdir -p "$ROOT/docs"
STATUS="$ROOT/docs/graphify-setup-status.txt"
status() { printf '%s\n' "$*" | tee -a "$STATUS"; }
printf 'JODARIS Graphify setup\n%s\nRoot: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$ROOT" > "$STATUS"
CLI="$(command -v graphify || true)"
if [ -z "$CLI" ] && [ -x "$HOME/.local/bin/graphify" ]; then CLI="$HOME/.local/bin/graphify"; fi
if [ -z "$CLI" ]; then
  if [ "$ALLOW_INSTALL" -ne 1 ]; then
    status 'PENDING: No Graphify CLI found. Existing website and development skill are usable.'
    status 'To allow a new tool installation, rerun with --install-tool. No installation was attempted.'
    exit 3
  fi
  if command -v uv >/dev/null 2>&1; then uv tool install graphifyy;
  elif command -v pipx >/dev/null 2>&1; then pipx install graphifyy;
  else status 'PENDING: Neither uv nor pipx is available. No package manager was installed.'; exit 3; fi
  CLI="$(command -v graphify || true)"
  if [ -z "$CLI" ] && [ -x "$HOME/.local/bin/graphify" ]; then CLI="$HOME/.local/bin/graphify"; fi
fi
if [ -z "$CLI" ]; then status 'PENDING: Graphify is not on PATH. Open a configured terminal and rerun.'; exit 3; fi
status "CLI: $CLI"
if VERSION="$("$CLI" --version 2>&1)"; then status "Version: $VERSION";
else status 'WARNING: CLI version command failed; no install will be attempted.'; exit 3; fi

# Only current-root ancestors inside the current Git root are automatically inherited.
GITROOT="$(git -C "$ROOT" rev-parse --show-toplevel 2>/dev/null || true)"
status "Enclosing Git root: ${GITROOT:-none detected}"
FOUND=''
LEGACY=''
SCAN="$ROOT"
while :; do
  if [ -f "$SCAN/.agents/skills/graphify/SKILL.md" ]; then FOUND="$SCAN/.agents/skills/graphify"; break; fi
  if [ -z "$LEGACY" ] && [ -f "$SCAN/.codex/skills/graphify/SKILL.md" ]; then LEGACY="$SCAN/.codex/skills/graphify"; fi
  [ -n "$GITROOT" ] && [ "$SCAN" != "$GITROOT" ] && [ "$SCAN" != '/' ] || break
  SCAN="$(dirname "$SCAN")"
done
if [ -z "$FOUND" ] && [ -f "$HOME/.agents/skills/graphify/SKILL.md" ]; then FOUND="$HOME/.agents/skills/graphify"; fi
if [ -z "$LEGACY" ] && [ -f "$HOME/.codex/skills/graphify/SKILL.md" ]; then LEGACY="$HOME/.codex/skills/graphify"; fi
if [ -n "$FOUND" ]; then
  status "REUSED: $FOUND/SKILL.md"
  status 'Presence is verified; activation still needs verification inside Codex.'
elif [ -n "$LEGACY" ]; then
  status "LEGACY SKILL FOUND: $LEGACY/SKILL.md"
  status 'PENDING: Review its contents and expose it through a supported .agents/skills location in the local agent session.'
  status 'No legacy skill, interpreter path, or global setting was changed.'
  exit 3
else
  if [ -e "$ROOT/.agents/skills/graphify" ] || [ -L "$ROOT/.agents/skills/graphify" ]; then
    status 'PENDING: Local Graphify folder exists without a readable SKILL.md; manual reconciliation required.'; exit 3
  fi
  HELP="$("$CLI" install --help 2>&1)" || { status 'PENDING: Cannot inspect installer help.'; exit 3; }
  if ! printf '%s\n' "$HELP" | grep -q -- '--project'; then
    status 'PENDING: Existing Graphify lacks --project. No upgrade/global install was performed.'; exit 3
  fi
  if ! printf '%s\n' "$HELP" | grep -q -- '--platform'; then
    status 'PENDING: Existing Graphify lacks --platform. No install was performed.'; exit 3
  fi
  # Snapshot affected instructions before calling the version-checked upstream installer.
  mkdir -p "$ROOT/.setup-backups"
  if [ -f "$ROOT/AGENTS.md" ]; then
    cp "$ROOT/AGENTS.md" "$ROOT/.setup-backups/AGENTS.pre-graphify.$(date -u '+%Y%m%dT%H%M%SZ').$$.md"
  fi
  "$CLI" install --project --platform codex
  if [ -f "$ROOT/.agents/skills/graphify/SKILL.md" ]; then
    status 'REGISTERED: .agents/skills/graphify/SKILL.md'
  elif [ -f "$ROOT/.codex/skills/graphify/SKILL.md" ]; then
    status 'LEGACY OUTPUT: .codex/skills/graphify/SKILL.md; verify discovery in your Codex version.'
  else status 'PENDING: Installer returned without a recognized skill output; inspect before claiming completion.'; exit 3; fi
fi
status 'Graph: NOT GENERATED by this script.'
status 'Next: open Codex at the JODARIS root; use $graphify . after reviewing .graphifyignore.'
status 'No Git hooks, global agent settings, AWS resources, or production deployments were changed by this script.'
