import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { docsEdition } from "./scripts/docs-edition";
const companyDocs = docsEdition() !== "public";

const sidebars: SidebarsConfig = {
  commandsSidebar: [
    ...(companyDocs ? ["index"] : []),
    {
      type: "category",
      label: "ci Commands",
      link: { type: "doc", id: "ci/index" },
      items: [{ type: "autogenerated", dirName: "ci" }],
    },
    ...(companyDocs
      ? ([
          {
            type: "category",
            label: "dev commands",
            customProps: { audience: "developer" },
            link: { type: "doc", id: "dev/index" },
            items: [{ type: "autogenerated", dirName: "dev" }],
          },
        ] satisfies SidebarsConfig[string])
      : []),
  ],
};

export default sidebars;
