import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Navigation for the private contributor-facing documentation surface. */
const companySidebars: SidebarsConfig = {
  cloudIgniterDevelopersSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default companySidebars;
