import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Navigation for skill content sourced from the repository's skill folders. */
const skillsSidebars: SidebarsConfig = {
  skillsSidebar: [
    {
      type: "category",
      label: "Repository Skills",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "agents/skills" }],
    },
    {
      type: "category",
      label: "Codex Skills",
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "codex/skills" }],
    },
  ],
};

export default skillsSidebars;
