import type { CiBuildCanonicalInput, CiCanonicalRecord, CiMetricConfig, CiTraceLoggerOptions } from "@ci-core/types";
export declare abstract class CiTraceLoggerBase {
    protected filePath?: string;
    protected endpoint: string;
    protected enabled: boolean;
    protected source: "server" | "client";
    protected prettyWave: boolean;
    protected truncateRate: number;
    protected metrics: Required<CiMetricConfig>;
    protected debug: boolean;
    protected tag?: string;
    private readonly timers;
    constructor(options: CiTraceLoggerOptions);
    protected abstract ciEmitRecord(record: CiCanonicalRecord): void;
    protected abstract ciEmitWaveBanner(banner: string): void;
    protected ciMaybeTruncateOnWave(): void;
    log(entry: Record<string, unknown>): void;
    wave(label?: string, extra?: Record<string, unknown>): void;
    start(label: string, base?: Record<string, unknown>): string;
    stop(handle: string, extra?: Record<string, unknown>): void;
    startTimer(label: string, base?: Record<string, unknown>): (_extra?: Record<string, unknown>) => void;
    time<T>(label: string, fn: () => Promise<T> | T, base?: Record<string, unknown>): Promise<T>;
    setEnabled(value: boolean): void;
    setFilePath(absPath: string): void;
    setEndpoint(url: string): void;
    setTag(tag: string): void;
    protected ciNowMs(): number;
    protected ciSafeStringify(input: unknown): string;
    protected ciWithTagQuery(tag: string): string;
    private ciFormatNameForType;
    private ciFormatMetricFor;
    protected ciBuildCanonical(input: CiBuildCanonicalInput): CiCanonicalRecord;
    private ciIsValidLogEntryType;
    ciLog(entry: Record<string, unknown>): void;
    ciWave(label?: string, extra?: Record<string, unknown>): void;
    ciStart(label: string, base?: Record<string, unknown>): string;
    ciStop(handle: string, extra?: Record<string, unknown>): void;
    ciStartTimer(label: string, base?: Record<string, unknown>): (_extra?: Record<string, unknown>) => void;
    ciTime<T>(label: string, fn: () => Promise<T> | T, base?: Record<string, unknown>): Promise<T>;
}
//# sourceMappingURL=ci-trace-logger-base.d.ts.map