import {
  CI_DEFAULT_REWRITE_SUBDOMAIN_TO_TENANT_PATH,
  CI_DEFAULT_TENANT_BASE_PATH,
  CI_DEFAULT_TENANT_ID_COOKIE_NAME,
  CI_DEFAULT_TENANT_ID_HEADER_NAME,
  CI_DEFAULT_TENANT_LOOKUP_PATH,
  CI_DEFAULT_TENANT_MODE_COOKIE_NAME,
  CI_DEFAULT_TENANT_MODE_HEADER_NAME,
  CI_DEFAULT_TENANT_NOT_FOUND_PATH,
  CI_DEFAULT_TENANT_ROUTING_MODE,
  CI_DEFAULT_TENANT_SCOPE_COOKIE_NAME,
  CI_DEFAULT_TENANT_SCOPE_HEADER_NAME,
  CI_DEFAULT_TENANT_STATUS_COOKIE_NAME,
  CI_DEFAULT_TENANT_STATUS_HEADER_NAME,
  CI_DEFAULT_TENANT_SUSPENDED_PATH,
  CI_DEFAULT_TENANT_URL_STRATEGY,
  CI_DEFAULT_VALIDATE_TENANT,
  CI_DEFAULT_WRITE_TENANT_COOKIE,
} from "@cloudigniter/core/lib";

import type { CiTenantRoutingOptions } from "@cloudigniter/core/types";

export const CI_DEFAULT_TENANT_ROUTING_OPTIONS: Required<CiTenantRoutingOptions> =
  {
    enabled: false,
    mode: CI_DEFAULT_TENANT_ROUTING_MODE,
    basePath: CI_DEFAULT_TENANT_BASE_PATH,
    idCookieName: CI_DEFAULT_TENANT_ID_COOKIE_NAME,
    idHeaderName: CI_DEFAULT_TENANT_ID_HEADER_NAME,
    modeCookieName: CI_DEFAULT_TENANT_MODE_COOKIE_NAME,
    modeHeaderName: CI_DEFAULT_TENANT_MODE_HEADER_NAME,
    scopeCookieName: CI_DEFAULT_TENANT_SCOPE_COOKIE_NAME,
    scopeHeaderName: CI_DEFAULT_TENANT_SCOPE_HEADER_NAME,
    statusCookieName: CI_DEFAULT_TENANT_STATUS_COOKIE_NAME,
    statusHeaderName: CI_DEFAULT_TENANT_STATUS_HEADER_NAME,
    writeTenantCookie: CI_DEFAULT_WRITE_TENANT_COOKIE,
    rewriteSubdomainToTenantPath: CI_DEFAULT_REWRITE_SUBDOMAIN_TO_TENANT_PATH,
    lookupPath: CI_DEFAULT_TENANT_LOOKUP_PATH,
    validateTenant: CI_DEFAULT_VALIDATE_TENANT,
    notFoundPath: CI_DEFAULT_TENANT_NOT_FOUND_PATH,
    suspendedPath: CI_DEFAULT_TENANT_SUSPENDED_PATH,
    infoPageStrategy: CI_DEFAULT_TENANT_URL_STRATEGY,

    rootDomains: [],
    reservedSubdomains: ["www"],
    reservedTenantSlugs: [],
  };
